// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfqsllfmsbfqtmnicebd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmcXNsbGZtc2JmcXRtbmljZWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTQ1NjQsImV4cCI6MjA2ODk5MDU2NH0.v2_m9ErN9n2FKMUthzB9t2G3a7sRuHW3gzpM2HaBriQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});